export const LOCAL_STORAGE_TOKEN_LOGIN = ''
export const BASE_API_URL = ''
export const BASE_EXAMPLE_API_URL = ''
export const BASE_AWS_S3_BUCKER_API = 'https://enion-bucket.s3.ap-southeast-1.amazonaws.com'
export const CONSUMPTION_FILE = 'Joni-consumption.csv'
export const MARKET_PRICE_FILE = 'Day-ahead+Prices_2022.csv'
export const START_DATE = '2022-01-01'
export const END_DATE = '2022-12-31'
